# Generated by Django 2.2.10 on 2020-02-16 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_modified', models.DateTimeField(verbose_name='修改时间')),
                ('gmt_created', models.DateTimeField(verbose_name='创建时间')),
                ('title', models.CharField(max_length=1024, verbose_name='标题')),
                ('pic_urls', models.CharField(max_length=2048, verbose_name='图片url')),
                ('content', models.CharField(max_length=1024, verbose_name='详情内容')),
            ],
            options={
                'db_table': 'leeyum_article',
            },
        ),
        migrations.CreateModel(
            name='CategoryStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_modified', models.DateTimeField(verbose_name='修改时间')),
                ('gmt_created', models.DateTimeField(verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='类目名字')),
                ('intro', models.CharField(max_length=256, verbose_name='类目介绍')),
                ('parent', models.IntegerField(default=0, verbose_name='上级id')),
            ],
            options={
                'db_table': 'leeyum_category',
            },
        ),
        migrations.CreateModel(
            name='TagStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_modified', models.DateTimeField(verbose_name='修改时间')),
                ('gmt_created', models.DateTimeField(verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='标签名字')),
                ('intro', models.CharField(max_length=256, verbose_name='标签介绍')),
            ],
            options={
                'db_table': 'leeyum_tag',
            },
        ),
        migrations.CreateModel(
            name='UserStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_modified', models.DateTimeField(verbose_name='修改时间')),
                ('gmt_created', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'db_table': 'leeyum_user',
            },
        ),
        migrations.CreateModel(
            name='CommentStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_modified', models.DateTimeField(verbose_name='修改时间')),
                ('gmt_created', models.DateTimeField(verbose_name='创建时间')),
                ('comment_parents', models.IntegerField(default=0, verbose_name='评论回复上层id')),
                ('comment_message', models.CharField(max_length=1024, verbose_name='评论信息')),
                ('comment_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leeyum.ArticleStore')),
                ('comment_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leeyum.UserStore')),
            ],
            options={
                'db_table': 'leeyum_comment',
            },
        ),
        migrations.AddField(
            model_name='articlestore',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leeyum.CategoryStore'),
        ),
        migrations.AddField(
            model_name='articlestore',
            name='tags',
            field=models.ManyToManyField(to='leeyum.TagStore'),
        ),
    ]
