# Generated by Django 2.2.10 on 2020-02-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestore',
            name='gmt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='articlestore',
            name='gmt_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='categorystore',
            name='gmt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='categorystore',
            name='gmt_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='commentstore',
            name='gmt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='commentstore',
            name='gmt_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='tagstore',
            name='gmt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tagstore',
            name='gmt_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='userstore',
            name='gmt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userstore',
            name='gmt_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
