# Generated by Django 2.2.10 on 2020-02-21 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0003_auto_20200221_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorystore',
            name='parent',
            field=models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_category', to='leeyum.CategoryStore'),
        ),
    ]
