# Generated by Django 2.2.10 on 2020-02-23 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0004_auto_20200221_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlestore',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间'),
        ),
    ]
