# Generated by Django 2.2.10 on 2020-02-23 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0005_articlestore_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestore',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
    ]
