# Generated by Django 2.2.10 on 2020-02-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0006_auto_20200223_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlestore',
            name='tags',
        ),
        migrations.AddField(
            model_name='articlestore',
            name='tags',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='标签 拍平存储'),
        ),
    ]
