# Generated by Django 2.2.10 on 2020-02-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0007_auto_20200225_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlestore',
            name='status',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
    ]
