# Generated by Django 2.2.10 on 2020-02-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0008_articlestore_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestore',
            name='content',
            field=models.CharField(blank=True, max_length=10240, null=True, verbose_name='详情内容'),
        ),
    ]
