# Generated by Django 2.2.10 on 2020-03-04 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0009_auto_20200229_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('action_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='动作名')),
                ('record_data', models.CharField(blank=True, max_length=128, null=True, verbose_name='记录值')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leeyum_action_definition',
            },
        ),
        migrations.CreateModel(
            name='ActionTimeRecorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('day_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='天记录值')),
                ('week_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='周记录值（7天）')),
                ('month_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='月记录值（30天）')),
                ('total_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='总记录')),
                ('week_ttl', models.IntegerField(default=1, verbose_name='周倒计时')),
                ('month_ttl', models.IntegerField(default=1, verbose_name='月倒计时')),
                ('record_date', models.DateField(auto_now_add=True, verbose_name='记录时间')),
                ('action_definition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actions', to='leeyum.ActionDefinition')),
            ],
            options={
                'db_table': 'leeyum_action_time_recorder',
                'unique_together': {('action_definition', 'record_date')},
            },
        ),
    ]
