# Generated by Django 2.2.10 on 2020-03-05 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0010_actiondefinition_actiontimerecorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentstore',
            name='comment_type',
            field=models.IntegerField(default=0, verbose_name='评论类型'),
        ),
        migrations.AlterField(
            model_name='commentstore',
            name='comment_parents',
            field=models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_comment', to='leeyum.CommentStore'),
        ),
    ]
