# Generated by Django 2.2.10 on 2020-03-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0011_auto_20200305_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentstore',
            old_name='comment_parents',
            new_name='comment_parent',
        ),
    ]
