# Generated by Django 2.2.10 on 2020-03-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0012_auto_20200305_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstore',
            name='like_article',
            field=models.ManyToManyField(to='leeyum.ArticleStore'),
        ),
    ]
