# Generated by Django 2.2.10 on 2020-03-07 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0014_auto_20200307_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportstore',
            name='report_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leeyum.ArticleStore'),
        ),
        migrations.AlterField(
            model_name='reportstore',
            name='report_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leeyum.CommentStore'),
        ),
    ]
