# Generated by Django 2.2.10 on 2020-03-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0015_auto_20200307_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlestore',
            name='liked_times',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏次数'),
        ),
        migrations.AddField(
            model_name='articlestore',
            name='viewed_times',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='浏览次数'),
        ),
    ]
