# Generated by Django 2.2.10 on 2020-03-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0016_auto_20200310_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlestore',
            name='liked_times',
        ),
    ]
