# Generated by Django 2.2.10 on 2020-03-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0017_remove_articlestore_liked_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentstore',
            name='report_level',
            field=models.IntegerField(default=0, verbose_name='举报等级'),
        ),
    ]
