# Generated by Django 2.2.10 on 2020-03-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0019_articlestore_report_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentstore',
            name='report_level',
            field=models.IntegerField(default=3, verbose_name='举报等级'),
        ),
    ]
