# Generated by Django 2.2.10 on 2020-03-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0021_auto_20200313_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentstore',
            name='comment_parent',
        ),
    ]
