# Generated by Django 2.2.10 on 2020-03-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0022_remove_commentstore_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressNewsStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('news_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='标题')),
                ('news_target_url', models.CharField(blank=True, max_length=128, null=True, verbose_name='单个目标url')),
                ('news_tag', models.CharField(blank=True, max_length=64, null=True, verbose_name='单个标签')),
            ],
            options={
                'db_table': 'leeyum_express_news',
            },
        ),
    ]
