# Generated by Django 2.2.10 on 2020-03-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0023_expressnewsstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstore',
            name='accept_publish_article_recommend_to_others',
            field=models.BooleanField(default=True, verbose_name='允许发布信息推荐给他人'),
        ),
        migrations.AddField(
            model_name='userstore',
            name='accept_recommended_message',
            field=models.BooleanField(default=True, verbose_name='允许接收短信推荐'),
        ),
        migrations.AddField(
            model_name='userstore',
            name='student_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='userstore',
            name='teams',
            field=models.ManyToManyField(related_name='team_members', to='leeyum.ArticleStore'),
        ),
    ]
