# Generated by Django 2.2.10 on 2020-03-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0024_auto_20200318_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorystore',
            name='pic_url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='类目图片'),
        ),
    ]
