# Generated by Django 2.2.10 on 2020-03-25 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0027_auto_20200322_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=1024, null=True, verbose_name='广告标题')),
                ('pic_urls', models.CharField(max_length=2048, null=True, verbose_name='图片url')),
                ('content', models.CharField(blank=True, max_length=10240, null=True, verbose_name='广告内容')),
                ('viewed_times', models.IntegerField(blank=True, default=0, null=True, verbose_name='浏览次数')),
                ('tags', models.CharField(blank=True, max_length=1024, null=True, verbose_name='标签 拍平存储')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('status', models.IntegerField(default=0, verbose_name='广告状态')),
                ('publisher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leeyum_advert',
            },
        ),
    ]
