# Generated by Django 2.2.10 on 2020-03-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0028_advertstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertstore',
            name='viewed_times',
        ),
        migrations.AddField(
            model_name='advertstore',
            name='is_advert',
            field=models.BooleanField(default=True, verbose_name='广告标志'),
        ),
    ]
