# Generated by Django 2.2.10 on 2020-03-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0029_auto_20200328_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertstore',
            name='publisher',
        ),
        migrations.AddField(
            model_name='advertstore',
            name='viewed_times',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='浏览次数'),
        ),
    ]
