# Generated by Django 2.2.10 on 2020-03-28 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leeyum', '0030_auto_20200328_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertstore',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
